### ISSUE TITLE
Exception in Nuix 9

### ISSUE THREAD

**Issue by JuicyDragon** [Nuix/Tiered-Report#8]
I haven't yet reproduced this myself, but script seems to be throwing the following exception.  My initial thought is this is due to slightly changed behavior in Java core lib due to Nuix moving to Java 11 (I believe) in Nuix 9

```
Error occured in provided block:
null
java.util.ConcurrentModificationException
	at java.util.HashMap.computeIfAbsent(java/util/HashMap.java:1134)
	at com.nuix.tieredreport.TieredReportData.getItemInfo(com/nuix/tieredreport/TieredReportData.java:74)
	at com.nuix.tieredreport.TieredReportData.scanItems(com/nuix/tieredreport/TieredReportData.java:282)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(jdk/internal/reflect/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:566)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:426)
	at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:293)
	at RUBY.<main>(C:\Users\NancyNuix\AppData\Roaming\Nuix\Scripts\TieredReport.nuixscript\TieredReport.rb:514)
	at org.jruby.RubyProc.call(org/jruby/RubyProc.java:318)
	at org.jruby.javasupport.Java$ProcToInterface.callProc(org/jruby/javasupport/Java.java:1136)
	at org.jruby.javasupport.Java$ProcToInterface.access$300(org/jruby/javasupport/Java.java:1113)
	at org.jruby.javasupport.Java$ProcToInterface$ConcreteMethod.call(org/jruby/javasupport/Java.java:1174)
	at com.nuix.nx.dialogs.ProgressDialog.forBlock(com/nuix/nx/dialogs/ProgressDialog.java:421)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(jdk/internal/reflect/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:566)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:426)
	at org.jruby.javasupport.JavaMethod.invokeStaticDirect(org/jruby/javasupport/JavaMethod.java:358)
	at RUBY.<main>(C:\Users\NancyNuix\AppData\Roaming\Nuix\Scripts\TieredReport.nuixscript\TieredReport.rb:356)
	at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:1240)
	at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:1244)
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(org/jruby/embed/internal/EmbedEvalUnitImpl.java:118)
	at org.jruby.embed.jsr223.JRubyEngine.eval(org/jruby/embed/jsr223/JRubyEngine.java:118)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(jdk/internal/reflect/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:566)
	at com.nuix.script.e.a(com/nuix/script/SourceFile:62)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.nuix.script.e.a(com/nuix/script/SourceFile:59)
	at com.sun.proxy.$Proxy71.eval(com/sun/proxy/$Proxy71)
	at com.nuix.script.a.a(com/nuix/script/SourceFile:290)
	at com.nuix.investigator.script.m.e(com/nuix/investigator/script/SourceFile:323)
	at com.nuix.investigator.script.m.c(com/nuix/investigator/script/SourceFile:274)
	at com.nuix.investigator.script.m.doInBackground(com/nuix/investigator/script/SourceFile:177)
	at javax.swing.SwingWorker$1.call(javax/swing/SwingWorker.java:304)
	at java.util.concurrent.FutureTask.run(java/util/concurrent/FutureTask.java:264)
	at javax.swing.SwingWorker.run(javax/swing/SwingWorker.java:343)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurrent/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurrent/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java/lang/Thread.java:834)
```

**Comment by JuicyDragon** [comment]
Fixed in [v1.26.0](https://github.com/Nuix/Tiered-Report/releases/tag/v1.26.0)
